/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/ui/BaseButton.vue')['default']
    BaseForm: typeof import('./src/components/form/BaseForm.vue')['default']
    BaseFormInput: typeof import('./src/components/form/BaseFormInput.vue')['default']
    BaseFormRadioGroup: typeof import('./src/components/form/BaseFormRadioGroup.vue')['default']
    BaseFormSelect: typeof import('./src/components/form/BaseFormSelect.vue')['default']
    BaseModal: typeof import('./src/components/ui/BaseModal.vue')['default']
    Button: typeof import('primevue/button')['default']
    Divider: typeof import('primevue/divider')['default']
    Footer: typeof import('./src/components/layout/Footer.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    OrderStepper: typeof import('./src/components/OrderStepper.vue')['default']
    Password: typeof import('primevue/password')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    Step: typeof import('primevue/step')['default']
    StepList: typeof import('primevue/steplist')['default']
    StepPanel: typeof import('primevue/steppanel')['default']
    StepPanels: typeof import('primevue/steppanels')['default']
    Stepper: typeof import('primevue/stepper')['default']
    ToggleButton: typeof import('primevue/togglebutton')['default']
  }
}
